[package]
name = "whip-up"
version = "0.1.0"
authors = ["Sam Privett"]
edition = "2018"

[dependencies]
clap = "2.33.0"
proc-macro2 = "1.0.9"
quote = "1.0.3"

[dependencies.syn]
version = "1.0.16"
features = ["extra-traits", "full"]
